### ISSUE TITLE
test_to_openssl_ failures on Fedora 21

### ISSUE THREAD

**Issue by sngardner** [warner/python-ecdsa#46]
All of the `test_to_openssl_*` tests fail for me on Fedora 21 (and my CentOS 6.7 box as well).

```
======================================================================
ERROR: test_to_openssl_secp256k1 (ecdsa.test_pyecdsa.OpenSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 384, in test_to_openssl_secp256k1
    self.do_test_to_openssl(SECP256k1)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 408, in do_test_to_openssl
    run_openssl("dgst %s -verify t/pubkey.der -keyform DER -signature t/data.sig t/data.txt" % mdarg)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 34, in run_openssl
    (OPENSSL, cmd, p.returncode, stdout))
SubprocessError: cmd 'openssl dgst -SHA1 -verify t/pubkey.der -keyform DER -signature t/data.sig t/data.txt' failed: rc=1, stdout/err was unable to load key file
```

Is there a workaround? I'm trying to package this as an RPM and would really like to run the tests as part of the `%check` portion of the RPM build process.

**Comment by tomato42** [comment]
python3 incompatibility?

**Comment by sngardner** [comment]
It doesn't look like it - the invocation of `openssl dgst` seems to be failing.

Is python3 a requirement for ecdsa to work correctly?

**Comment by tomato42** [comment]
no, it's not python

Fedora version of OpenSSL didn't have support for all curves, just P-256, P-384 and P-521.
But later some curves were added, like the quoted secp256k1 (with openssl-1.0.1k-12.fc21): https://bugzilla.redhat.com/show_bug.cgi?id=1021898 so I'm not sure what's happening

**Comment by warner** [comment]
Do *all* of the tests fail? I'm wondering if it's maybe just the missing curves. I know redhat has traditionally been rather wary of elliptic curves, and has commented out the supporting code in a lot of the libraries they ship.

I suppose we could add some code to probe the `openssl dgst` command first, to figure out which curves it supports, and then set those tests to SKIP instead of having them fail outright. I don't know if `openssl` has a command to ask "which curves do you support?", so it might require running a command which then fails, to discover what it supports.

**Comment by tomato42** [comment]
Yes, openssl does have such command: `openssl ecparam -list_curves` and on current Fedora 22 (openssl-1.0.1k-12.fc22.x86_64) it does reply with a list that includes secp256k1

**Comment by sngardner** [comment]
Here's the output from my openssl:
```
sgardner@buildenv python-ecdsa-python-ecdsa-0.13 % openssl ecparam -list_curves
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  prime256v1: X9.62/SECG curve over a 256 bit prime field
```

These are all of the test failures:
```
======================================================================
ERROR: test_from_openssl_nist192p (ecdsa.test_pyecdsa.OpenSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 335, in test_from_openssl_nist192p
    return self.do_test_from_openssl(NIST192p)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 356, in do_test_from_openssl
    run_openssl("ecparam -name %s -genkey -out t/privkey.pem" % curvename)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 34, in run_openssl
    (OPENSSL, cmd, p.returncode, stdout))
SubprocessError: cmd 'openssl ecparam -name prime192v1 -genkey -out t/privkey.pem' failed: rc=1, stdout/err was unable to create curve (prime192v1)


======================================================================
ERROR: test_from_openssl_nist224p (ecdsa.test_pyecdsa.OpenSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 337, in test_from_openssl_nist224p
    return self.do_test_from_openssl(NIST224p)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 356, in do_test_from_openssl
    run_openssl("ecparam -name %s -genkey -out t/privkey.pem" % curvename)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 34, in run_openssl
    (OPENSSL, cmd, p.returncode, stdout))
SubprocessError: cmd 'openssl ecparam -name secp224r1 -genkey -out t/privkey.pem' failed: rc=1, stdout/err was unable to create curve (secp224r1)


======================================================================
ERROR: test_from_openssl_secp256k1 (ecdsa.test_pyecdsa.OpenSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 345, in test_from_openssl_secp256k1
    return self.do_test_from_openssl(SECP256k1)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 356, in do_test_from_openssl
    run_openssl("ecparam -name %s -genkey -out t/privkey.pem" % curvename)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 34, in run_openssl
    (OPENSSL, cmd, p.returncode, stdout))
SubprocessError: cmd 'openssl ecparam -name secp256k1 -genkey -out t/privkey.pem' failed: rc=1, stdout/err was unable to create curve (secp256k1)


======================================================================
ERROR: test_to_openssl_nist192p (ecdsa.test_pyecdsa.OpenSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 374, in test_to_openssl_nist192p
    self.do_test_to_openssl(NIST192p)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 408, in do_test_to_openssl
    run_openssl("dgst %s -verify t/pubkey.der -keyform DER -signature t/data.sig t/data.txt" % mdarg)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 34, in run_openssl
    (OPENSSL, cmd, p.returncode, stdout))
SubprocessError: cmd 'openssl dgst -SHA1 -verify t/pubkey.der -keyform DER -signature t/data.sig t/data.txt' failed: rc=1, stdout/err was unable to load key file


======================================================================
ERROR: test_to_openssl_nist224p (ecdsa.test_pyecdsa.OpenSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 376, in test_to_openssl_nist224p
    self.do_test_to_openssl(NIST224p)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 408, in do_test_to_openssl
    run_openssl("dgst %s -verify t/pubkey.der -keyform DER -signature t/data.sig t/data.txt" % mdarg)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 34, in run_openssl
    (OPENSSL, cmd, p.returncode, stdout))
SubprocessError: cmd 'openssl dgst -SHA1 -verify t/pubkey.der -keyform DER -signature t/data.sig t/data.txt' failed: rc=1, stdout/err was unable to load key file


======================================================================
ERROR: test_to_openssl_secp256k1 (ecdsa.test_pyecdsa.OpenSSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 384, in test_to_openssl_secp256k1
    self.do_test_to_openssl(SECP256k1)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 408, in do_test_to_openssl
    run_openssl("dgst %s -verify t/pubkey.der -keyform DER -signature t/data.sig t/data.txt" % mdarg)
  File "/svn/packages/python-ecdsa/trunk/sources/python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py", line 34, in run_openssl
    (OPENSSL, cmd, p.returncode, stdout))
SubprocessError: cmd 'openssl dgst -SHA1 -verify t/pubkey.der -keyform DER -signature t/data.sig t/data.txt' failed: rc=1, stdout/err was unable to load key file
```

**Comment by sngardner** [comment]
I also tried to patch out the tests which do not match my above supported curves but it doesn't seem to work. Here's my (admittedly very naive) patch if anyone is curious:
```
```
diff -rupN python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py python-ecdsa-python-ecdsa-0.13-TOS-2136-test-fix/ecdsa/test_pyecdsa.py
--- python-ecdsa-python-ecdsa-0.13/ecdsa/test_pyecdsa.py	2015-02-07 12:19:14.000000000 -0600
+++ python-ecdsa-python-ecdsa-0.13-XXX-XXXX-test-fix/ecdsa/test_pyecdsa.py	2015-09-18 16:35:08.630832527 -0500
@@ -331,18 +331,12 @@ class OpenSSL(unittest.TestCase):
     # vk: 3:OpenSSL->python  4:python->OpenSSL
     # sig: 5:OpenSSL->python 6:python->OpenSSL
 
-    def test_from_openssl_nist192p(self):
-        return self.do_test_from_openssl(NIST192p)
-    def test_from_openssl_nist224p(self):
-        return self.do_test_from_openssl(NIST224p)
     def test_from_openssl_nist256p(self):
         return self.do_test_from_openssl(NIST256p)
     def test_from_openssl_nist384p(self):
         return self.do_test_from_openssl(NIST384p)
     def test_from_openssl_nist521p(self):
         return self.do_test_from_openssl(NIST521p)
-    def test_from_openssl_secp256k1(self):
-        return self.do_test_from_openssl(SECP256k1)
 
     def do_test_from_openssl(self, curve):
         curvename = curve.openssl_name
```

**Comment by opoplawski** [comment]
I would suggest just dropping support for 192 and 224 bit curves - see https://bugzilla.redhat.com/show_bug.cgi?id=1067697

**Comment by tomato42** [comment]
the tests need to be updated to detect which curves does openssl support (using `-list_curves`) and then [skip](https://docs.pytest.org/en/latest/skipping.html) tests with curves not supported by the local version of openssl

both the `test_from_openssl_` and `test_to_openssl_` tests need to get this treatment
